/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTableRouteImport } from './routes/_authenticated/table'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGridsRouteImport } from './routes/_authenticated/grids'
import { Route as AuthenticatedHabitsNewRouteImport } from './routes/_authenticated/habits/new'
import { Route as AuthenticatedHabitsHabitIdEditRouteImport } from './routes/_authenticated/habits/$habitId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTableRoute = AuthenticatedTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGridsRoute = AuthenticatedGridsRouteImport.update({
  id: '/grids',
  path: '/grids',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsNewRoute = AuthenticatedHabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsHabitIdEditRoute =
  AuthenticatedHabitsHabitIdEditRouteImport.update({
    id: '/habits/$habitId/edit',
    path: '/habits/$habitId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/grids': typeof AuthenticatedGridsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/table': typeof AuthenticatedTableRoute
  '/habits/new': typeof AuthenticatedHabitsNewRoute
  '/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/grids': typeof AuthenticatedGridsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/table': typeof AuthenticatedTableRoute
  '/': typeof AuthenticatedIndexRoute
  '/habits/new': typeof AuthenticatedHabitsNewRoute
  '/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/grids': typeof AuthenticatedGridsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/table': typeof AuthenticatedTableRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/habits/new': typeof AuthenticatedHabitsNewRoute
  '/_authenticated/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/grids'
    | '/settings'
    | '/table'
    | '/habits/new'
    | '/habits/$habitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/grids'
    | '/settings'
    | '/table'
    | '/'
    | '/habits/new'
    | '/habits/$habitId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/grids'
    | '/_authenticated/settings'
    | '/_authenticated/table'
    | '/_authenticated/'
    | '/_authenticated/habits/new'
    | '/_authenticated/habits/$habitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/table': {
      id: '/_authenticated/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AuthenticatedTableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grids': {
      id: '/_authenticated/grids'
      path: '/grids'
      fullPath: '/grids'
      preLoaderRoute: typeof AuthenticatedGridsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits/new': {
      id: '/_authenticated/habits/new'
      path: '/habits/new'
      fullPath: '/habits/new'
      preLoaderRoute: typeof AuthenticatedHabitsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits/$habitId/edit': {
      id: '/_authenticated/habits/$habitId/edit'
      path: '/habits/$habitId/edit'
      fullPath: '/habits/$habitId/edit'
      preLoaderRoute: typeof AuthenticatedHabitsHabitIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedGridsRoute: typeof AuthenticatedGridsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTableRoute: typeof AuthenticatedTableRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHabitsNewRoute: typeof AuthenticatedHabitsNewRoute
  AuthenticatedHabitsHabitIdEditRoute: typeof AuthenticatedHabitsHabitIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGridsRoute: AuthenticatedGridsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTableRoute: AuthenticatedTableRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHabitsNewRoute: AuthenticatedHabitsNewRoute,
  AuthenticatedHabitsHabitIdEditRoute: AuthenticatedHabitsHabitIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
